version: '3.8'

services:
  legacy_scoring:
    build: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    network_mode: "host"
